name: white_rabbit_challenge
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  connectivity_plus: 2.2.1
  dartz: 0.10.1
  dio: 4.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_screenutil: 5.3.1
  freezed_annotation: 1.1.0
  get_it: 7.2.0
  google_fonts: 2.3.1
  hive: 2.0.6
  hive_flutter: 1.1.0
  http: 0.13.3
  injectable: 1.5.3
  json_annotation: 4.4.0
  json_serializable: 6.1.5
  shimmer: 2.0.0

dev_dependencies:
  build_runner: 2.1.7
  flutter_lints: 1.0.4
  freezed: 1.1.1
  hive_generator: 1.1.2
  injectable_generator: 1.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/loading_gif.gif
